# Generated by Django 4.0.4 on 2022-04-30 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now=True, unique=True, verbose_name='Date Published')),
            ],
        ),
    ]
